version: "3.8"

services:
  database:
    image: mongo:6.0
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - db_data:/data/db
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "mongosh", "--username", "${MONGO_INITDB_ROOT_USERNAME}", "--password", "${MONGO_INITDB_ROOT_PASSWORD}", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend
    container_name: backend
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@database:27017/${MONGO_DB_NAME}?authSource=admin"
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend_net
      - frontend_net

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://backend:3000
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - frontend_net

networks:
  backend_net:
    driver: bridge
  frontend_net:
    driver: bridge

volumes:
  db_data:
